"""Make Migrations

Revision ID: 00c3e17c2fbb
Revises: bb0df4519ad0
Create Date: 2025-02-27 10:28:18.922536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00c3e17c2fbb'
down_revision: Union[str, None] = 'bb0df4519ad0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
