"""Add CurrencyEnum

Revision ID: 0ba1ce858177
Revises: d36740429394
Create Date: 2025-03-19 16:44:16.556704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ba1ce858177'
down_revision: Union[str, None] = 'd36740429394'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('purchased_currency', sa.Enum('USD', 'UZS', name='currencyenum'), nullable=True))
    op.drop_column('item', 'purchased_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('purchased_price', postgresql.ENUM('USD', 'UZS', name='currencyenum'), autoincrement=False, nullable=True))
    op.drop_column('item', 'purchased_currency')
    # ### end Alembic commands ###
