"""Add transactions table

Revision ID: 0e62f55926b1
Revises: ee94c530f367
Create Date: 2025-03-24 21:02:02.123858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e62f55926b1'
down_revision: Union[str, None] = 'ee94c530f367'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('item_purchased_quantity', sa.Integer(), nullable=True))
    op.add_column('item', sa.Column('item_purchased_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('item', sa.Column('item_sold_quantity', sa.Integer(), nullable=True))
    op.add_column('item', sa.Column('item_sold_date', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('item', 'item_quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('item_quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('item', 'item_sold_date')
    op.drop_column('item', 'item_sold_quantity')
    op.drop_column('item', 'item_purchased_date')
    op.drop_column('item', 'item_purchased_quantity')
    # ### end Alembic commands ###
