"""Tables created

Revision ID: 21024b23d5fc
Revises: d31021d9bc60
Create Date: 2025-02-06 15:16:23.066520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21024b23d5fc'
down_revision: Union[str, None] = 'd31021d9bc60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name_uz', sa.String(), nullable=False),
    sa.Column('category_name_ru', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_inn_number', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_category_id', sa.Integer(), nullable=True),
    sa.Column('item_brand_id', sa.Integer(), nullable=True),
    sa.Column('item_model_id', sa.Integer(), nullable=True),
    sa.Column('item_color', sa.String(length=50), nullable=True),
    sa.Column('item_ram', sa.Integer(), nullable=True),
    sa.Column('item_is_new', sa.Enum('NEW', 'USED', name='itemconditionenum'), nullable=True),
    sa.Column('item_description', sa.Text(), nullable=True),
    sa.Column('item_imei', sa.String(length=20), nullable=True),
    sa.Column('item_imei_2', sa.String(length=20), nullable=True),
    sa.Column('item_imei_status', sa.Enum('REGISTERED', 'UNREGISTERED', name='itemimeienum'), nullable=True),
    sa.Column('item_imei_status_2', sa.Enum('REGISTERED', 'UNREGISTERED', name='itemimeienum'), nullable=True),
    sa.Column('item_seria_number', sa.String(), nullable=True),
    sa.Column('item_purchased_price', sa.Float(), nullable=False),
    sa.Column('item_selling_price', sa.Float(), nullable=True),
    sa.Column('item_quantity', sa.Integer(), nullable=True),
    sa.Column('shop_info_id', sa.Integer(), nullable=True),
    sa.Column('customer_info', sa.Text(), nullable=True),
    sa.Column('previous_owner_info', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['item_brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['item_category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['item_model_id'], ['model.id'], ),
    sa.ForeignKeyConstraint(['shop_info_id'], ['shop_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    op.drop_table('shop_info')
    op.drop_table('model')
    op.drop_table('category')
    op.drop_table('brand')
    # ### end Alembic commands ###
