"""Make Migrations

Revision ID: 21e71248b13c
Revises: 671f8862ed87
Create Date: 2025-02-18 11:41:20.230897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21e71248b13c'
down_revision: Union[str, None] = '671f8862ed87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('input_inn_number', sa.Column('org_inn_number', sa.String(), nullable=False))
    op.drop_column('input_inn_number', 'inn_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('input_inn_number', sa.Column('inn_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('input_inn_number', 'org_inn_number')
    # ### end Alembic commands ###
