"""Make migrations

Revision ID: 26ac222c50b9
Revises: 
Create Date: 2025-03-12 16:40:50.063847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26ac222c50b9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name_uz', sa.String(), nullable=False),
    sa.Column('category_name_ru', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('register_date', sa.String(), nullable=True),
    sa.Column('org_status', sa.String(), nullable=True),
    sa.Column('registration_authority', sa.String(), nullable=True),
    sa.Column('inn_number', sa.Integer(), nullable=True),
    sa.Column('thsht_info', sa.String(), nullable=True),
    sa.Column('dbibt_info', sa.String(), nullable=True),
    sa.Column('ifut_info', sa.String(), nullable=True),
    sa.Column('authorized_fund', sa.Float(), nullable=True),
    sa.Column('org_email', sa.String(), nullable=True),
    sa.Column('org_phone_number', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('company_address', sa.String(), nullable=True),
    sa.Column('founders', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_firstname', sa.String(), nullable=True),
    sa.Column('user_lastname', sa.String(), nullable=True),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.Column('user_phone_number', sa.String(), nullable=True),
    sa.Column('user_password', sa.String(), nullable=True),
    sa.Column('user_image', sa.String(), nullable=True),
    sa.Column('user_gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='usergenderenum'), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('role', sa.Enum('GUEST', 'USER', name='userroleenum'), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('verification_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_phone_number')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_user_email'), 'user', ['user_email'], unique=True)
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_category_id', sa.Integer(), nullable=True),
    sa.Column('item_brand_id', sa.Integer(), nullable=True),
    sa.Column('item_model_id', sa.Integer(), nullable=True),
    sa.Column('item_color', sa.String(length=50), nullable=False),
    sa.Column('item_ram', sa.Integer(), nullable=True),
    sa.Column('item_is_new', sa.Enum('NEW', 'USED', name='itemconditionenum'), nullable=True),
    sa.Column('item_description', sa.Text(), nullable=True),
    sa.Column('item_imei', sa.String(length=20), nullable=True),
    sa.Column('item_imei_2', sa.String(length=20), nullable=True),
    sa.Column('item_imei_status', sa.Enum('REGISTERED', 'UNREGISTERED', name='itemimeienum'), nullable=True),
    sa.Column('item_imei_status_2', sa.Enum('REGISTERED', 'UNREGISTERED', name='itemimeienum'), nullable=True),
    sa.Column('item_seria_number', sa.String(), nullable=True),
    sa.Column('item_purchased_price', sa.Float(), nullable=False),
    sa.Column('item_selling_price', sa.Float(), nullable=True),
    sa.Column('item_quantity', sa.Integer(), nullable=True),
    sa.Column('shop_info_id', sa.Integer(), nullable=True),
    sa.Column('customer_info', sa.Text(), nullable=True),
    sa.Column('previous_owner_info', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['item_brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['item_category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['item_model_id'], ['model.id'], ),
    sa.ForeignKeyConstraint(['shop_info_id'], ['shop_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    op.drop_index(op.f('ix_user_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_table('shop_info')
    op.drop_table('model')
    op.drop_table('category')
    op.drop_table('brand')
    # ### end Alembic commands ###
