"""Tables created

Revision ID: 3b7c27e4e560
Revises: 277a6e6ca99c
Create Date: 2025-02-16 22:01:52.350909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b7c27e4e560'
down_revision: Union[str, None] = '277a6e6ca99c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('input_inn_number',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_inn_number', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('brand', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('brand', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('category', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('category', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('item', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('item', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('item', 'item_color',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.add_column('model', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('model', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('shop_info', sa.Column('register_date', sa.String(), nullable=True))
    op.add_column('shop_info', sa.Column('org_status', sa.String(), nullable=True))
    op.add_column('shop_info', sa.Column('registration_authority', sa.String(), nullable=True))
    op.add_column('shop_info', sa.Column('inn_number', sa.Integer(), nullable=True))
    op.add_column('shop_info', sa.Column('thsht_info', sa.String(), nullable=True))
    op.add_column('shop_info', sa.Column('dbibt_info', sa.String(), nullable=True))
    op.add_column('shop_info', sa.Column('ifut_info', sa.String(), nullable=True))
    op.add_column('shop_info', sa.Column('authorized_fund', sa.Float(), nullable=True))
    op.add_column('shop_info', sa.Column('org_email', sa.String(), nullable=True))
    op.add_column('shop_info', sa.Column('org_phone_number', sa.String(), nullable=True))
    op.add_column('shop_info', sa.Column('company_name', sa.String(), nullable=True))
    op.add_column('shop_info', sa.Column('company_address', sa.String(), nullable=True))
    op.add_column('shop_info', sa.Column('founders', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('shop_info', 'seller_inn_number')
    op.add_column('user', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.add_column('shop_info', sa.Column('seller_inn_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('shop_info', 'founders')
    op.drop_column('shop_info', 'company_address')
    op.drop_column('shop_info', 'company_name')
    op.drop_column('shop_info', 'org_phone_number')
    op.drop_column('shop_info', 'org_email')
    op.drop_column('shop_info', 'authorized_fund')
    op.drop_column('shop_info', 'ifut_info')
    op.drop_column('shop_info', 'dbibt_info')
    op.drop_column('shop_info', 'thsht_info')
    op.drop_column('shop_info', 'inn_number')
    op.drop_column('shop_info', 'registration_authority')
    op.drop_column('shop_info', 'org_status')
    op.drop_column('shop_info', 'register_date')
    op.drop_column('model', 'updated_at')
    op.drop_column('model', 'created_at')
    op.alter_column('item', 'item_color',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('item', 'updated_at')
    op.drop_column('item', 'created_at')
    op.drop_column('category', 'updated_at')
    op.drop_column('category', 'created_at')
    op.drop_column('brand', 'updated_at')
    op.drop_column('brand', 'created_at')
    op.drop_table('input_inn_number')
    # ### end Alembic commands ###
