"""Make migrations

Revision ID: 3eda96fa6650
Revises: 8a7e02a7a41f
Create Date: 2025-03-18 11:45:30.251777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eda96fa6650'
down_revision: Union[str, None] = '8a7e02a7a41f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('item_item_model_id_fkey', 'item', type_='foreignkey')
    op.drop_constraint('item_item_category_id_fkey', 'item', type_='foreignkey')
    op.drop_constraint('item_item_brand_id_fkey', 'item', type_='foreignkey')
    op.create_foreign_key(None, 'item', 'model', ['item_model_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'item', 'category', ['item_category_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'item', 'brand', ['item_brand_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.create_foreign_key('item_item_brand_id_fkey', 'item', 'brand', ['item_brand_id'], ['id'])
    op.create_foreign_key('item_item_category_id_fkey', 'item', 'category', ['item_category_id'], ['id'])
    op.create_foreign_key('item_item_model_id_fkey', 'item', 'model', ['item_model_id'], ['id'])
    # ### end Alembic commands ###
