"""Make migrations

Revision ID: 421b79ae5512
Revises: 8c380fc13e61
Create Date: 2025-03-19 10:44:18.954370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '421b79ae5512'
down_revision: Union[str, None] = '8c380fc13e61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('brand_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'model', 'brand', ['brand_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'model', type_='foreignkey')
    op.drop_column('model', 'brand_id')
    # ### end Alembic commands ###
