"""Add CurrencyEnum

Revision ID: 42e0b77f1f44
Revises: 0ba1ce858177
Create Date: 2025-03-20 07:27:09.494543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42e0b77f1f44'
down_revision: Union[str, None] = '0ba1ce858177'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
