"""Make Migrations

Revision ID: 4582567ab4aa
Revises: 2eca8fe53633
Create Date: 2025-02-26 20:02:52.195997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4582567ab4aa'
down_revision: Union[str, None] = '2eca8fe53633'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_email', sa.String(), nullable=False))
    op.drop_index('ix_user_username', table_name='user')
    op.create_index(op.f('ix_user_user_email'), 'user', ['user_email'], unique=True)
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_user_email'), table_name='user')
    op.create_index('ix_user_username', 'user', ['username'], unique=True)
    op.drop_column('user', 'user_email')
    # ### end Alembic commands ###
