"""Make Migrations

Revision ID: 66b4db5f05a4
Revises: 9e8f60235eac
Create Date: 2025-03-04 11:18:13.321301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66b4db5f05a4'
down_revision: Union[str, None] = '9e8f60235eac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('role', sa.String(), nullable=True))
    op.add_column('user', sa.Column('ip_address', sa.String(), nullable=True))
    op.alter_column('user', 'user_phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.alter_column('user', 'user_phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user', 'ip_address')
    op.drop_column('user', 'role')
    op.drop_column('user', 'is_verified')
    # ### end Alembic commands ###
