"""Make Migrations

Revision ID: 671f8862ed87
Revises: c2fe0d5c3e3e
Create Date: 2025-02-18 11:36:32.275350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '671f8862ed87'
down_revision: Union[str, None] = 'c2fe0d5c3e3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
