"""Make migrations

Revision ID: 85c1c4252049
Revises: 421b79ae5512
Create Date: 2025-03-19 16:33:48.798825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85c1c4252049'
down_revision: Union[str, None] = '421b79ae5512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('purchased_price', sa.Enum('USD', 'UZS', name='currencyenum'), nullable=True))
    op.add_column('item', sa.Column('selling_currency', sa.Enum('USD', 'UZS', name='currencyenum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'selling_currency')
    op.drop_column('item', 'purchased_price')
    # ### end Alembic commands ###
