"""Make migrations

Revision ID: 8a7e02a7a41f
Revises: 2d366051f75b
Create Date: 2025-03-17 11:54:59.086266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a7e02a7a41f'
down_revision: Union[str, None] = '2d366051f75b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'verification_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('verification_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
