"""Make migrations

Revision ID: 8c380fc13e61
Revises: 3eda96fa6650
Create Date: 2025-03-18 21:22:35.540143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c380fc13e61'
down_revision: Union[str, None] = '3eda96fa6650'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'brand', 'category', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'brand', type_='foreignkey')
    op.drop_column('brand', 'category_id')
    # ### end Alembic commands ###
