"""Add item_is_sold to Item model

Revision ID: 8db4709ebd1a
Revises: bcc52a085bfc
Create Date: 2025-03-24 13:08:09.798449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8db4709ebd1a'
down_revision: Union[str, None] = 'bcc52a085bfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('item_sold_price', sa.Float(), nullable=True))
    op.add_column('item', sa.Column('sold_currency', sa.Enum('USD', 'UZS', name='currencyenum'), nullable=True))
    op.drop_column('item', 'item_selling_price')
    op.drop_column('item', 'selling_currency')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('selling_currency', postgresql.ENUM('USD', 'UZS', name='currencyenum'), autoincrement=False, nullable=True))
    op.add_column('item', sa.Column('item_selling_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('item', 'sold_currency')
    op.drop_column('item', 'item_sold_price')
    # ### end Alembic commands ###
