"""Add customer info to SellItemSchema

Revision ID: 9d4363d9d534
Revises: bc23eee82e96
Create Date: 2025-03-24 15:14:20.079313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d4363d9d534'
down_revision: Union[str, None] = 'bc23eee82e96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
