"""Initial migration

Revision ID: a9a39e5b3fdb
Revises: 
Create Date: 2025-03-27 17:55:22.081173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9a39e5b3fdb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('income', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('expense', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('official_usd_rate', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('custom_usd_rate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('used_usd_rate', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    # ### end Alembic commands ###
