"""Edit models CurrencyEnum

Revision ID: aa1ead3a4419
Revises: ac869cd7b044
Create Date: 2025-03-24 12:31:07.887467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa1ead3a4419'
down_revision: Union[str, None] = 'ac869cd7b044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
