"""Add item_is_sold to Item model

Revision ID: bcc52a085bfc
Revises: aa1ead3a4419
Create Date: 2025-03-24 13:04:47.215402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcc52a085bfc'
down_revision: Union[str, None] = 'aa1ead3a4419'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('item_is_sold', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'item_is_sold')
    # ### end Alembic commands ###
