"""create brand table

Revision ID: f795fd3abba2
Revises: bf4dd0829448
Create Date: 2025-02-17 16:20:14.340292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f795fd3abba2'
down_revision: Union[str, None] = 'bf4dd0829448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('input_inn_number', sa.Column('inn_number', sa.String(), nullable=False))
    op.drop_column('input_inn_number', 'seller_inn_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('input_inn_number', sa.Column('seller_inn_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('input_inn_number', 'inn_number')
    # ### end Alembic commands ###
